### ISSUE TITLE
Make a shorter introduction for the case study article

### ISSUE THREAD

**Issue by lubc** [ombulabs/blog.ombulabs.com#112]
The `How We Helped Predictable Revenue Scale` article is taking too much space in the [index page](https://www.ombulabs.com/blog). We should only show a few lines there.

![screen shot 2017-10-16 at 12 19 46](https://user-images.githubusercontent.com/7442887/31619991-573df8a4-b296-11e7-8ca5-c34134991a94.png)

**Comment by etagwerker** [comment]
Just fixed this 👍 

https://www.ombulabs.com/blog
