### ISSUE TITLE
Header is not responsive anymore

### ISSUE THREAD

**Issue by mauro-oto** [ombulabs/blog.ombulabs.com#45]
For some reason, the header stopped being responsive, and you now have to scroll to the right and left to see the entire header, it should not behave like that. Maybe we could just show the isotope or decrease the font size for smaller resolutions?

**Comment by etagwerker** [comment]
It seems to cause problems in iOS too. Check it out. 

![slack for ios upload png](https://cloud.githubusercontent.com/assets/17584/13176204/0d212efa-d6ef-11e5-8048-5b0dd8dae056.jpeg)

**Comment by mauro-oto** [comment]
@etagwerker could you check if it's still causing problems? It seems to be fixed when browsing with Chrome on Android.

**Comment by etagwerker** [comment]
@mauro-oto It seems to be fixed now. I just checked!
