### ISSUE TITLE
Blog post idea: IMAP Extended Fields

### ISSUE THREAD

**Issue by mauro-oto** [ombulabs/blog.ombulabs.com#51]
Ruby's native `Net::IMAP` library doesn't allow you to fetch attributes it doesn't recognize, like Gmail's `X-GM-THRID`, it raises a parse error. The workaround is monkeypatching the class, like shown here: https://github.com/gmailgem/gmail/blob/master/lib/gmail/imap_extensions.rb#L8-L53.

**Comment by etagwerker** [comment]
@mauro-oto I think this was solved by this article: http://www.ombulabs.com/blog/ruby/imap/a-comprehensive-guide-to-interacting-with-imap-using-ruby.html

**Comment by mauro-oto** [comment]
@etagwerker this referred to special IMAP attributes, which I didn't reference in the post you linked. I never wrote this anyway because it feels way too niche, it's not very interesting, and we ended up solving the problem that prompted this blog post in a different way. We can close it though, I agree :+1:
