### ISSUE TITLE
Dead external links

### ISSUE THREAD

**Issue by mauro-oto** [ombulabs/blog.ombulabs.com#85]
```
➜  blog git:(master) ✗ bundle exec htmlproofer ./_site --only-4xx --url-ignore "/blog/,/#content/"
Running ["ScriptCheck", "ImageCheck", "LinkCheck"] on ["./_site"] on *.html...

Checking 206 external links...
Ran on 75 files!

- ./_site/maintenance/conventions/standard-getting-started.html
  *  External link https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/bin/setup failed: 404 No error
- ./_site/rails/maintenance/ten-steps-to-evaluate-a-rails-project.html
  *  External link https://docs.codeclimate.com/docs/gpa failed: 404 No error
htmlproofer 3.3.1 | Error:  HTML-Proofer found 2 failures!
```

@etagwerker there are two posts you made which link to 404 pages. For the first link we should look for a stable Rails release instead of master, as it's likely to change over time. For the second one, it looks like it's now `/docs/ratings` instead. 

Do you think we should add this gem to the project and setup something like Travis to tell us when there are dead links?

**Comment by etagwerker** [comment]
@mauro-oto Yeah, I think it's a good idea to setup Travis for this project to check for dead links.
